name: IAS Scan
on:
  push:
    branches: [ master ]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - id: my-scan
        uses: nmorrissey-r7/insightappsec-scan-github-actions@v1.3.3
        with:
          region: us
          api-key: ${{ secrets.IAS_API_KEY }}
          scan-config-id: '0f688e3a-6d8e-4a71-9e82-6ac3efdac213'
          scan-timeout-mins: 1
          vuln-query: "vulnerability.severity = 'HIGH'"
      - name: Upload findings
        if: always()
        run: echo "${{ steps.my-scan.outputs.scan-findings }}"
  deploy:
    runs-on: ubuntu-latest
    needs: [scan]
    steps:
      - name: Deploy artifact
        run: echo "Deploying..."
